version: "3"
services:
  reverseproxy:
    build:
    context: .
    image: sunilkrishnatry/reverseproxy 
  backend_user:
    build:
      context: ../../udacity-c3-restapi-user
    image: sunilkrishnatry/udacity-c3-restapi-user
  backend_feed:
    build:
      context: ../../udacity-c3-restapi-feed  
    image: sunilkrishnatry/udacity-c3-restapi-feed
  frontend:
    build:
      context: ../../udacity-c3-frontend  
    image: sunilkrishnatry/udacity-c3-frontend::local
